'use strict';
const fs = require('fs');
const path = require('path');
global.document = { addEventListener() {} };
global.window = global;
const source = fs.readFileSync(path.join(__dirname, '..', 'js/core/app.js'), 'utf8');
(0, eval)(`${source}\n;globalThis.__actionRouterApp = App;`);
const App = global.__actionRouterApp;
const el = (tagName, attrs = {}) => ({ tagName, getAttribute: name => attrs[name] || '' });
const button = el('BUTTON', { 'data-action': 'AppointmentsFeature.saveAppointment' });
const keyboardCard = el('DIV', { 'data-action': 'App.navigate', 'data-key': 'Enter, space' });
const input = el('INPUT', { 'data-action': 'SettingsFeature.setName' });
const liveInput = el('INPUT', { 'data-action': 'AppointmentsFeature.debouncedCustomerSearch', 'data-event': 'input' });
const count = (element, events) => events.filter(type => App.shouldDispatchActionEvent(element, type)).length;
const assert = (condition, message) => { if (!condition) throw new Error(message); };
assert(count(button, ['click']) === 1, 'pointer click should dispatch once');
assert(count(button, ['keydown', 'keyup', 'click']) === 1, 'native keyboard activation should dispatch only its synthetic click');
assert(count(keyboardCard, ['keydown', 'keyup']) === 1, 'data-key target should dispatch once on keydown');
assert(count(input, ['click', 'input', 'change', 'blur']) === 1, 'ordinary form control should dispatch once on change');
assert(count(liveInput, ['click', 'input', 'change', 'blur']) === 1, 'explicit live input should dispatch only on input');
console.log('ACTION ROUTER TEST PASSED');
